export const rows = [
    {
      "id": 1,
      "registrer id": "1234684",
      "age": 45,
      "name": "Leanne Graham",
      "username": "Bret",
      "email": "Sincere@april.biz",
      "address": "Kulas Light",
        "city": "Gwenborough",
        "zipcode": "92998-3874",
      "phone": "1-770-736-8031 x56442",
    },
    {
      "id": 2,
      "age": 54,
      "registrer id": "1234684",
      "name": "Ervin Howell",
      "username": "Antonette",
      "email": "Shanna@melissa.tv",
      "address": "Victor Plains",
        "city": "Wisokyburgh",
        "zipcode": "90566-7771",
      "phone": "010-692-6593 x09125",
    },
    {
      "id": 3,
      "age": 33,
      "registrer id": "1234684",
      "name": "Clementine Bauch",
      "username": "Samantha",
      "email": "Nathan@yesenia.net",
      "address": "Douglas Extension",
        "city": "McKenziehaven",
        "zipcode": "59590-4157",
      "phone": "1-463-123-4447",
    },
    {
      "id": 4,
      "age": 22,
      "registrer id": "1234684",
      "name": "Patricia Lebsack",
      "username": "Karianne",
      "email": "Julianne.OConner@kory.org",
      "address": "Hoeger Mall",
        "suite": "Apt. 692",
        "city": "South Elvis",
        "zipcode": "53919-4257",
      "phone": "493-170-9623 x156",
    },
    {
      "id": 5,
      "age": 37,
      "registrer id": "1234684",
      "name": "Chelsey Dietrich",
      "username": "Kamren",
      "email": "Lucio_Hettinger@annie.ca",
      "address": "Skiles Walks",
        "city": "Roscoeview",
        "zipcode": "33263",
      "phone": "(254)954-1289",
    },
    {
      "id": 6,
      "age": 24,
      "registrer id": "1234684",
      "name": "Mrs. Dennis Schulist",
      "username": "Leopoldo_Corkery",
      "email": "Karley_Dach@jasper.info",
      "address": "Norberto Crossing",
        "city": "South Christy",
        "zipcode": "23505-1337",
      "phone": "1-477-935-8478 x6430",
    },
    {
      "id": 7,
      "age": 36,
      "registrer id": "1234684",
      "name": "Kurtis Weissnat",
      "username": "Elwyn.Skiles",
      "email": "Telly.Hoeger@billy.biz",
      "address": "Rex Trail",
        "city": "Howemouth",
        "zipcode": "58804-1099",
      "phone": "210.067.6132",
    },
    {
      "id": 8,
      "age": 27,
      "registrer id": "1234684",
      "name": "Nicholas Runolfsdottir V",
      "username": "Maxime_Nienow",
      "email": "Sherwood@rosamond.me",
      "address":"Ellsworth Summit",
        "city": "Aliyaview",
        "zipcode": "45169",
      "phone": "586.493.6943 x140",
    },
    {
      "id": 9,
      "age": 35,
      "registrer id": "1234684",
      "name": "Glenna Reichert",
      "username": "Delphine",
      "email": "Chaim_McDermott@dana.io",
      "address":  "Dayna Park",
        "city": "Bartholomebury",
        "zipcode": "76495-3109",
      "phone": "(775)976-6794 x41206",
    },
    {
      "id": 10,
      "age": 39,
      "registrer id": "1234684",
      "name": "Glenna Reichert",
      "username": "Delphine",
      "email": "Chaim_McDermott@dana.io",
      "address":  "Dayna Park",
        "city": "Bartholomebury",
        "zipcode": "76495-3109",
      "phone": "(775)976-6794 x41206",
    },
    {
        "id": 11,
        "age": 67,
        "registrer id": "1234684",
        "name": "Mrs. Dennis Schulist",
        "username": "Leopoldo_Corkery",
        "email": "Karley_Dach@jasper.info",
        "address": "Norberto Crossing",
          "city": "South Christy",
          "zipcode": "23505-1337",
        "phone": "1-477-935-8478 x6430",
      },
  ] 

export   const columns = [
    {
      field: "id",
      headerName: "id",
      width: 30,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "registrer id",
      headerName: "registrer id",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "name",
      headerName: "name",
      align: "center",
      headerAlign: "center",
    },
      { field: "age", headerName: "age", align: "center", headerAlign: "center"},
    {
      field: "email",
      headerName: "email",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "phone",
      headerName: "phone number",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "address",
      headerName: "address",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "city",
      headerName: "city",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "zipcode",
      headerName: "zip code",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
];
